export default Palette = {
  lightBlue: '#ADD8E6',
  lightRed: '#FFCCCC',
  blue: 0,
  red: 0,
  white: '#ffffff',
  lightGray: '#ADADAD',
  black: '#000000',
  gray: '#656565',
  lightestGray: '#D3D3D3',
  primaryBlueColor: '#1DCBF7',
  primaryBlueText: '#1DCBF7',
  borderRed: '#FF8B8B',
  textRed: '#FF3434',
  lightPrimary: '#EFEFF7',
  borderE2: '#E2E2E2',
  backgroundGray: '#E2E2E2',
  inputBorderGray: '#cdcdcd',
  paleGrayBorder: '#B3BFC2',
};
